exports.getMainPage = function(lista,date,ord)
{
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>About people</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red w3-centered">
                <h1>Lista de pessoas (${lista.length})</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr class="w3-amber">
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Idade</th>
                        <th>Sexo</th>
                        <th>Cidade</th>
                    </tr>`
    for(let i = 0; i < lista.length; i++)
    {
        pagHtml += `
                    <tr>
                        <td>${lista[i].id}</td>
                        <td>
                        <a href="http://localhost:7777/pessoas/${lista[i].id}">${lista[i].nome}
                        </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                    </tr>
        `
    }
    pagHtml += `
                </table>
            </div>
            <footer class="w3-container w3-red">
                <h5>Generated by pessoas-server: ${date}</h5>
                <a href="http://localhost:7777/">Página inicial</a>
            </footer>
        </div> 
    </body>
</html>
    `
    return pagHtml
}

exports.getPersonPage = function(pessoa,date)
{
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>About people</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-red w3-centered">
                <h1>Nome: ${pessoa.nome}</h1>
            </header>
            <div class="w3-container">`
    pagHtml += `
                <h2>ID: ${pessoa.id}</h2>
                <h2>Cidade: ${pessoa.morada.cidade}</h2>
                <h2>Idade: ${pessoa.idade}</h2>
                <h2>Sexo: ${pessoa.sexo}</h2>
                <h2>Profissao: ${pessoa.profissao}</h2>
    `
    // colocar aqui informação da pessoa recebida
    pagHtml += `
            </div>
            <footer class="w3-container w3-red">
                <h5>Generated by pessoas-server: ${date}</h5>
                <a href="http://localhost:7777/">Página inicial</a>
            </footer>
        </div> 
    </body>
</html>
    `
    return pagHtml
}

exports.getOptionsPage = function(listaOpcoes,date)
{
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>Opções</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-lime">
                <h1>Lista de opções</h1>
            </header>
            <div class="w3-container">
                <ol class="w3-ul w3-hoverable">`
    listaOpcoes.forEach(element => {
        pagHtml += `    
                            <li><a href="${element['link']}">${element['name']}</a></li>`
    });
    pagHtml+= `
                </ol>
            </div>
            <footer class="w3-container w3-lime">
                <h5>Generated by pessoas-server: ${date}</h5>
            </footer>
        </div> 
    </body>
</html>`
    return pagHtml
}

exports.getDistSexo = function(lista,date)
{
    var contagem1 = 
    {
        'masculino':0,
        'feminino':0,
        'outro':0
    }
    lista.forEach(elem => contagem1[elem.sexo]++)
    total = 0
    for(let sex in contagem1)
    {
        total += contagem1[sex]
    }
    contagem = []
    for(let sport in contagem1)
    {
        contagem.push([sport,contagem1[sport]])
    }
    contagem.sort(function (e1,e2) {return e2[1]-e1[1]})
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>Distribuição por sexo</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-purple">
                <h1>Distribuição por sexo</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr class="w3-blue">
                        <th>Sexo</th>
                        <th>Quantidade</th>
                        <th>Probabilidade</th>
                    </tr>`
    for(let i = 0; i < contagem.length; i++)
    {
        var s = contagem[i][0]
        var valor = contagem[i][1]
        var pro = Math.round(valor/total * 100 * 100) / 100
        pagHtml += `
                    <tr>
                        <td><a href="http://localhost:7777/pessoas/sex/${s}">${s}</a></td>
                        <td>${valor}</td>
                        <td>${pro}%</td>
                    </tr>
        `
    }
    pagHtml +=        `
                </table>
            </div>
            <footer class="w3-container w3-purple">
                <h5>Generated by pessoas-server: ${date}</h5>
                <a href="http://localhost:7777/">Página inicial</a>
            </footer>
        </div> 
    </body>
</html>`
    return pagHtml;
}

exports.getDistSport = function(lista,date)
{
    var contagem1 = {}
    lista.forEach(elem => 
    {
        elem.desportos.forEach(des => 
        {
            if(!(des in contagem1))
                contagem1[des] = 0; 
            contagem1[des]++
        })
    })
    total = 0
    for(let des in contagem1)
    {
        total += contagem1[des]
    }
    contagem = []
    for(let sport in contagem1)
    {
        contagem.push([sport,contagem1[sport]])
    }
    contagem.sort(function (e1,e2) {return e2[1]-e1[1]})
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>Distribuição por desporto</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-orange">
                <h1>Distribuição por desporto</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr class="w3-yellow">
                        <th>Desporto</th>
                        <th>Quantidade</th>
                        <th>Probabilidade</th>
                    </tr>`
    for(let i = 0; i < contagem.length; i++)
    {
        var s = contagem[i][0]
        var valor = contagem[i][1]
        var pro = Math.round(valor/total * 100 * 100) / 100
        pagHtml += `
                    <tr>
                        <td><a href="http://localhost:7777/pessoas/sport/${s}">${s}</a></td>
                        <td>${valor}</td>
                        <td>${pro}%</td>
                    </tr>
        `
    }
    pagHtml +=        `
                </table>
            </div>
            <footer class="w3-container w3-orange">
                <h5>Generated by pessoas-server: ${date}</h5>
                <a href="http://localhost:7777/">Página inicial</a>
            </footer>
        </div> 
    </body>
</html>`
    return pagHtml;
}

exports.getTop10Jobs = function(lista,date)
{
    var contagem = {}
    lista.forEach(elem => 
    {
        var pro = elem.profissao
        if(!(pro in contagem))
            contagem[pro] = 0
        contagem[pro]++
    })
    profstop = []
    for(let pro in contagem)
    {
        profstop.push([pro,contagem[pro]])
    }
    profstop.sort(function (e1,e2) {return e2[1]-e1[1]})
    profstop = profstop.slice(0,10)
    var pagHtml = `
<!DOCTYPE html>
<html>
    <head>
        <title>Top 10 profissões</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-gray">
                <h1>Top 10 profissões</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-centered">
                    <tr class="w3-black">
                        <th>Top</th>
                        <th>Profissão</th>
                        <th>Ocorrências</th>
                    </tr>`
    for(let i = 0; i < profstop.length; i++)
    {
        desp = profstop[i]
        pagHtml += `
                    <tr>
                        <td>${(i+1)}</td>
                        <td><a href="http://localhost:7777/pessoas/job/${desp[0]}">${desp[0]}</a> </td>
                        <td>${desp[1]}</td>
                    </tr>
        `
    }
    pagHtml +=        `
                </table>
            </div>
            <footer class="w3-container w3-gray">
                <h5>Generated by pessoas-server: ${date}</h5>
                <a href="http://localhost:7777/">Página inicial</a>
            </footer>
        </div> 
    </body>
</html>`
    return pagHtml;
}

var mypages = require('./mypages')

exports.getPeopleSex = function(lista,date, sex)
{
    return mypages.getMainPage(lista.filter((p) => p.sexo == sex),date)
}

exports.getPeopleSport = function(lista,date,sport)
{
    return mypages.getMainPage(lista.filter((p) => p.desportos.includes(sport)),date)
}

exports.getPeopleProf = function(lista,date,profession)
{
    return mypages.getMainPage(lista.filter((p) => p.profissao == profession),date)
}

/**
<!DOCTYPE html>
<html>
    <head>
        <title>Distribuição por sexo</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="/w3.css">
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-lime">
                <h1>Lista de opções</h1>
            </header>

            <footer class="w3-container w3-lime">
                <h5>Generated by pessoas-server: ${date}</h5>
            </footer>
        </div> 
    </body>
</html>
 */